name: Update JSON Files

on:
  repository_dispatch:
    types: [update_data]

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Update JSON files
        run: |
          echo '${{ github.event.client_payload.clientes }}' > public/data/clientes.json
          echo '${{ github.event.client_payload.compras }}' > public/data/compras.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/data/*.json
          git commit -m "Update JSON files" || exit 0
          git push 